language: go

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then 
      openssl aes-256-cbc -K $encrypted_eca6ec4b024e_key -iv $encrypted_eca6ec4b024e_iv -in appengine.json.enc -out appengine.json -d;
      sed -i 's/$TOKEN/'$SLACK_TOKEN'/g' app.yaml;
    fi

deploy:
  provider: gae
  keyfile: appengine.json
  project: womenwhogo-site
  skip_cleanup: true
  on: master
